#! /bin/sh

# Load previous colorscheme from pywal
wal -R &

# Create 10 desktop spaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Configure gaps and borders
bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Copied code from pywal docs lol
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

# Startup programs
sxhkd &
sleep 0.5 && $HOME/.config/polybar/launch.sh & # Polybar needs a slight delay to start properly
compton -b &
nm-applet &